vim.o.number = true
vim.o.relativenumber = true
vim.o.ignorecase = true
vim.o.smartcase = true
vim.o.wrap = true
vim.o.breakindent = true
vim.o.tabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = false
vim.o.cursorline = true
vim.o.scrolloff = 8
vim.o.undofile = true
vim.o.completeopt = "menu,menuone,noselect,noinsert,popup,fuzzy"
vim.schedule(function() vim.o.clipboard = "unnamedplus" end)
